name: Setup docker

description: Configure the docker workflow.

inputs:
  CR_PAT:
    required: true
  tag:
    required: true
    default: EDGE

outputs:
  tags:
    description: "tags"
    value: ${{ steps.meta.outputs.tags }}
  labels:
    description: "labels"
    value: ${{ steps.meta.outputs.labels }}

runs:
  using: composite
  steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Docker meta:${{ inputs.tag }}
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/stable-diffusion-webui
        tags: |
          dev,enable=${{ inputs.tag == 'master' }}
          ${{ inputs.tag }},enable=${{ inputs.tag != 'master' }}
          type=raw,value=latest,enable=${{ inputs.tag == 'dev' }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Create a Access Token with `read:packages` and `write:packages` scopes
    # CR_PAT
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.CR_PAT }}
