services:
  stable-diffusion-webui:
    container_name: stable-diffusion-webui
    image: ghcr.io/jim60105/stable-diffusion-webui:v1.9.3
    # build: .
    user: "1001:0"
    command:
      # https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings
      # https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/cmd_args.py
      #
      # Already configured in the entrypoint and should remain unchanged!!
      # --listen --port 7860 --data-dir /data
      #
      # Recommanded:
      - --xformers
      - --api
      - --allow-code
      - --no-half-vae
      # You may or may not need:
      ## Enable installing/modifying extensions from the UI, please pay attention to security considerations.
      - --enable-insecure-extension-access
      ## Optimizations
      ## https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Optimizations
      - --medvram
      - --opt-sdp-attention
      - --opt-sdp-no-mem-attention
      - --opt-split-attention
      - --opt-channelslast
    ports:
      - 7860:7860
    environment:
      # Use the volume to get better performance then bind mount.
      # And users should not touch these files in general.
      - SD_WEBUI_CACHE_FILE=/.cache/cache.json
      - SD_WEBUI_CACHE_DIR=/.cache
    tmpfs:
      - /tmp
    volumes:
      - cache:/.cache
      - repositories:/app/repositories
      - ./data:/data
      # Bind the following to the script folder to fix some extensions that do not respect the --data-dir.
      - ./data/config_states:/app/config_states
      - ./data/extensions:/app/extensions
      - ./data/models:/app/models
      # Using the long syntax requires the referenced file/folder to be created beforehand.
      - type: bind
        source: ./data/ui-config.json
        target: /app/ui-config.json
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

volumes:
  cache:
  repositories:
